INSERT INTO hy_basicdata(DATA_CODE,DATA_VALUE,DATA_TYPE) VALUES("2253","位置数据采集汇报设置",52);
INSERT INTO hy_basicdata(DATA_CODE,DATA_VALUE,DATA_TYPE) VALUES("2270","违规驾驶行为阀值设置",52);
INSERT INTO hy_basicdata(DATA_CODE,DATA_VALUE,DATA_TYPE) VALUES("22731","Can数据采集汇报设置",52);
INSERT INTO hy_basicdata(DATA_CODE,DATA_VALUE,DATA_TYPE) VALUES("22732","终端初始化参数设置",52);
INSERT INTO hy_basicdata(DATA_CODE,DATA_VALUE,DATA_TYPE) VALUES("2450","终端升级设置",52);