INSERT INTO hy_basictype(T_ID,T_NAME,T_COMMON) VALUES(70,"终端参数设置","终端参数设置");

INSERT INTO hy_basicdata(DATA_CODE,DATA_VALUE,DATA_TYPE) VALUES(101,"位置数据采集汇报设置",70);
INSERT INTO hy_basicdata(DATA_CODE,DATA_VALUE,DATA_TYPE) VALUES(102,"终端升级设置",70);
INSERT INTO hy_basicdata(DATA_CODE,DATA_VALUE,DATA_TYPE) VALUES(201,"CAN数据采集汇报设置",70);
INSERT INTO hy_basicdata(DATA_CODE,DATA_VALUE,DATA_TYPE) VALUES(202,"驾驶行为设置",70);
INSERT INTO hy_basicdata(DATA_CODE,DATA_VALUE,DATA_TYPE) VALUES(203,"终端初始化参数设置",70);

-- 设置hy_team中的PARENT_ID不为null
ALTER TABLE hy_team MODIFY  PARENT_ID bigint(20) NOT NULL;
-- 修改锁车状态值为null的数据改为0
UPDATE hy_car SET LOCK_STAUTS = 0 WHERE LOCK_STAUTS IS NULL;
-- 设置hy_car中的锁车状态值LOCK_STAUTS不为null 默认值为0
ALTER TABLE hy_car MODIFY  LOCK_STAUTS int(11) NOT NULL DEFAULT 0;
