ALTER TABLE hy_action
  ADD COLUMN A_ICON VARCHAR(200) DEFAULT NULL
COMMENT '菜单图标样式';
ALTER TABLE hy_action
  ADD COLUMN A_URL VARCHAR(200) DEFAULT NULL
COMMENT '菜单访问路径';
ALTER TABLE hy_action
  ADD A_DISPLAY_ORDER INT(11) DEFAULT NULL
COMMENT '菜单展示顺序';