CREATE TABLE `hy_risk` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REGION_ID` bigint(20) NOT NULL COMMENT '防控区域ID',
  `VEHICLE_ID` bigint(20) NOT NULL COMMENT '车辆ID',
  `RISK_TYPE` int(11) NOT NULL COMMENT '防控类型',
  `RISK_VALUE` int(20) NOT NULL COMMENT '防控值',
  `OPERATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  `OPERATE_USER` varchar(100) DEFAULT NULL COMMENT '操作人',
  `RISK_COMMON` varchar(200) DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`ID`),
  KEY `REGION_ID` (`REGION_ID`)
);
